openapi: 3.0.3
info:
  title: ФОП API
  description: |-
    Опис API для виконання операцій із ФОП
  version: 0.0.1
externalDocs:
  description: find out more about swagger.io
  url: http://swagger.io
servers:
  - url: http://localhost:4040/api/v1
    description: dev server
paths:
  /private-entrepreneur:
    get:
      summary: get all PEs
      description: зчитати всіх ФОП
      tags:
        - ФОП
      operationId: GetAllPes
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: './schemas/Pe.yaml#/Pes'
    post:
      tags:
        - ФОП
      summary: create new PE
      operationId: CreatePrivateEntrepreneur
      requestBody:
        description: Create new PE
        content:
          application/json:
            schema:
              $ref: './schemas/Pe.yaml#/Pe'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                #return PE object with all IDs filled in (generated by backend) 
                $ref: './schemas/Pe.yaml#/Pe'          
        '405':
          description: Invalid input
      security:    
        - flowersua_auth:
            - write:pe
            - read:pe

components:
  schemas:
    Pe:
      $ref: './schemas/Pe.yaml#/Pe'
    Error:
      $ref: './schemas/Error.yaml#/Error'

  securitySchemes:
    flowersua_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://localhost:4040/api/oauth/authorize
          scopes:
            write:pes: modify PEs in your account
            read:pes: read PEs
    api_key:
      type: apiKey
      name: api_key
      in: header