openapi: 3.0.3
info:
  title: ФОП API
  description: |-
    Опис API для виконання операцій із ФОП
  version: 0.0.1
externalDocs:
  description: find out more about swagger.io
  url: http://swagger.io
servers:
  - url: http://localhost:4040/api/v1
    description: dev server
paths:
  /pe:
    get:
      summary: get all PEs
      description: зчитати всіх ФОП
      tags:
        - ФОП
      operationId: getAllPs
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pes'
    post:
      tags:
        - ФОП
      summary: create new PE
      operationId: CreatePrivateEntrepreneur
      requestBody:
        description: Create new PE
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/pe'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pe'          
        '405':
          description: Invalid input
      security:    
        - flowersua_auth:
            - write:pe
            - read:pe


components:
  schemas:
    paymentMethod:
      type: object
      properties:
        paymentType:
          description: "Назва способу оплати, можливі значення: app, site"
          required: true
          type: string
          enum:
            - app
            - site
          default: app
        name:
          description: "Платіжна система/метод оплати, можливі значення: privat24, googlePay, portmone, applePay"
          type: string
          required: true
          enum:
            - privat24
            - googlePay
            - portmone
            - applePay
          default: privat24
    merchant:
      type: object
      properties:
        merchantId:
          description: 12 digits string
          type: string
          example: "i11111111111"
        publicKey:
          description: public key 6 digits
          type: string
          example: "123456"

    pe:
      required:
        - ipn
        - name
        - paymentMethod
        - merchant
      type: object
      properties:
        ipn:
          description: "ІПН"
          type: int64
          example: "1112454509"
        name:
          type: string
          example: "ФОП Петренко Є.І."
        comment:
          description: "Коментар, не обов'язкове поле" 
          example: "ТТ, не подключать, 202 369.92 оборот на 23.12.23"
        merchant:
          type: object
          $ref: '#/components/schemas/merchant'    
        paymentMethod:
           type: object
           $ref: '#/components/schemas/paymentMethod'
        fiscalGatewayId:
          default: "checkBox.ua"  
          description: "ID фіскального шлюзу"
          type: string
   
    pes:
      type: array
      items:
        $ref: '#/components/schemas/pe'
    error:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 500
        message:
          type: string
          example: "internal error"
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
  requestBodies:
    pe:
      description: pe object that needs to be created
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/pe'
  securitySchemes:
    flowersua_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://localhost:4040/api/oauth/authorize
          scopes:
            write:pes: modify PEs in your account
            read:pes: read PEs
    api_key:
      type: apiKey
      name: api_key
      in: header